BRC 2023 amendments
WPI-LNL/bylaws-and-regulations pull request #5
Opened 2023-03-31 00:25 UTC by Muirrum

Suggestions generated by the BRC process during 2023.

2023-03-31 00:27 UTC, i-am-gizm0 approved these changes

2023-04-13 17:48 UTC, benjamin-antupit requested changes

2023-04-13 17:48 UTC, benjamin-antupit commented on Bylaws_and_Regulations_of_WPI_Lens_and_Lights.tex
> +Director, Head Projectionist, Treasurer, Secretary, and Webmaster. The Executive Board is comprised of these officers and the Advisor.
```suggestion
The officers of the Club will be the President, Vice President, Technical Director, Head Projectionist, Treasurer, Secretary, and Webmaster. The Executive Board is comprised of these officers and the Advisor.
```

2023-04-13 17:48 UTC, benjamin-antupit commented on Bylaws_and_Regulations_of_WPI_Lens_and_Lights.tex
> +    serves as the liaison between the Club and any person(s) and/or organization(s) sponsoring an event. The Vice President is responsible for receiving and processing all work orders and for the org
```suggestion
\item The Vice President assists the President with duties as assigned and serves as the liaison between the Club and any person(s) and/or organization(s) sponsoring an event. The Vice President is responsible for receiving and processing all work orders and for the organization and operation of work parties.
```

2023-04-13 17:48 UTC, benjamin-antupit commented on Bylaws_and_Regulations_of_WPI_Lens_and_Lights.tex
> +    President, Technical Director, Head Projectionist, Treasurer, Secretary, Webmaster.
```suggestion
\item Officers will be elected in the following order: President, Vice President, Technical Director, Head Projectionist, Treasurer, Secretary, Webmaster.
```

2023-04-13 17:48 UTC, benjamin-antupit commented on Bylaws_and_Regulations_of_WPI_Lens_and_Lights.tex
> +    unless the crew chief is not fulfilling their responsibilities.
```suggestion
\item An officer will not interfere with a crew chief's operation at an event unless the crew chief is not fulfilling their responsibilities.
```

2023-04-13 17:48 UTC, benjamin-antupit commented on Bylaws_and_Regulations_of_WPI_Lens_and_Lights.tex
> +Note that the W1LNL callsign may not be used for general chat or ragchewing.
```suggestion
Note that the W1LNL callsign may not be used for general chat.
```

2023-04-13 17:48 UTC, benjamin-antupit commented on Bylaws_and_Regulations_of_WPI_Lens_and_Lights.tex
> +The W1LNL callsign does not confer any additional privileges beyond your amateur license. You may not use the W1LNL callsign to operate outside of your license privileges.
```suggestion
The W1LNL callsign does not confer any additional privileges beyond any member's amateur license. Members may not use the W1LNL callsign to operate outside of their license privileges.
```

2023-04-13 17:48 UTC, benjamin-antupit commented on Bylaws_and_Regulations_of_WPI_Lens_and_Lights.tex
> +Use of the W1LNL callsign is subject to the approval of the Repeater Manager. Members wishing to make use of the callsign should contact the Repeater Manager in advance of their planned usage. Author
```suggestion
Use of the W1LNL callsign is subject to the approval of the Repeater Manager or the Executive Board. Members wishing to make use of the callsign should contact the Repeater Manager or the Executive Board in advance of their planned usage. Authorization can be revoked at any time by the Repeater Manager or the Executive Board.
```

2023-04-13 17:48 UTC, benjamin-antupit commented on Bylaws_and_Regulations_of_WPI_Lens_and_Lights.tex
> +        management and communications.
```suggestion
    \item Card access is a privilege granted to members of the club. The Executive Board can revoke any card access within its purview. Should a member be found to be misusing their access, the Executive Board shall review their access accordingly.
    \item The President shall be responsible for working with relevant campus departments to maintain card access and communicating any changes in a timely manner.
    \item The Facilities Liaison can assist the President with card access management and communications.
```

2023-04-13 17:48 UTC, benjamin-antupit commented on Bylaws_and_Regulations_of_WPI_Lens_and_Lights.tex
> +\item No member shall begin an Independent Study Project related to the club without first consulting the Executive Board.
```suggestion
```

2023-04-13 17:48 UTC, benjamin-antupit commented on Bylaws_and_Regulations_of_WPI_Lens_and_Lights.tex
> +\item Absentee ballots will be accepted in the form of written communication containing an ordered list of names, abstain, or no confidence in descending preference, for each office. This written com
```suggestion
\item Absentee ballots will be accepted in the form of written communication containing an ordered list of names, abstain, or no confidence in descending preference, for each office. This written communication should be submitted to the person(s) counting votes in accordance with \cref{itm:votecounters} of this section. Absentee ballots for a given office must be received prior to the start of vote counting for that position. Absentee ballots will only be counted if the member submitting them is not currently present at the meeting. Absentee ballots shall not count towards quorum.
```

2023-04-13 18:01 UTC, benjamin-antupit commented on Bylaws_and_Regulations_of_WPI_Lens_and_Lights.tex
> +    office will be elected to that office.
```suggestion
\item Absentee ballots will be accepted in the form of written communication containing an ordered list of names, abstain, or no confidence in descending preference, for each office. This written communication should be submitted to the person(s) counting votes in accordance with \cref{itm:votecounters} of this section. Absentee ballots for a given office must be received prior to the start of vote counting for that position. Absentee ballots will only be counted if the member submitting them is not currently present at the meeting. Absentee ballots shall not count towards quorum. 
\item The first nominee to get greater than 50 percent of non-abstaining votes cast for an office will be elected to that office.
```

2023-04-13 18:01 UTC, benjamin-antupit commented on Bylaws_and_Regulations_of_WPI_Lens_and_Lights.tex
> +    unless the crew chief is not fulfilling their responsibilities.
```suggestion
\item An officer will not interfere with a crew chief's operation at an event unless the crew chief is not fulfilling their responsibilities.
```

2023-04-13 19:05 UTC, benjamin-antupit commented on Bylaws_and_Regulations_of_WPI_Lens_and_Lights.tex
> +\item Additional events or usages at the discretion of the Repeater Manager
```suggestion
\item Additional events or usages at the discretion of the Repeater Manager or Executive Board.
```

2023-04-14 14:56 UTC, benjamin-antupit approved these changes

2023-04-14 15:12 UTC, merged